Ready compare aging seasoft report data preprocessing

In [5]:
import pandas as pd
import numpy as np
import subprocess
import sys
import tkinter as tk
from tkinter import filedialog

In [6]:
e1 = pd.read_excel('/workspaces/PracticeMachineLearning/data/mixed_aging.xlsx')
e2 = pd.read_excel('/workspaces/PracticeMachineLearning/data/AP APPROVALS - 07.12.23.xlsx')

In [9]:
#rename last column of the aging to ensure it is names Company. <3
e1.columns = [*e1.columns[:-1], 'Company']

In [10]:
e1.head()

,Vendor,Invoice,S,*================,Unnamed: 4,Dates ===================*,Unnamed: 6,Unnamed: 7,Invoice.1,Discount,Payments,Balance,Company
0,PO #,NaN,T,Invoice,Due,Discount,Posting,Receipt,NaN,Available,NaN,Due,Ready
1,ACI001,"AC, INC.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ready
2,727283,121093,O,2023-07-09 00:00:00,2023-07-16 00:00:00,2023-07-09 00:00:00,2023-07-09 00:00:00,2023-07-09 00:00:00,93892.5,0,0,93892.5,Ready
3,ACI001,"AC, INC.",NaN,NaN,NaN,NaN,NaN,NaN,93892.5,0,0,93892.5,Ready
4,ALP001,ALPHA CHEMICAL SERVICES INC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ready

In [23]:
#replace all int values in the Vendor column with Nan
e1['Vendor'] = e1['Vendor'].mask(e1['Vendor'].apply(lambda x: isinstance(x, int)), np.nan)

In [24]:
# Drop rows that has 'S' or 'T' oin the 'S' column
e1 = e1[~e1['S'].isin(['S', 'T'])]

In [25]:
e1.head(50)

,Vendor,Invoice,S,*================,Unnamed: 4,Dates ===================*,Unnamed: 6,Unnamed: 7,Invoice.1,Discount,Payments,Balance,Company
1,ACI001,"AC, INC.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ready
2,NaN,121093,O,2023-07-09 00:00:00,2023-07-16 00:00:00,2023-07-09 00:00:00,2023-07-09 00:00:00,2023-07-09 00:00:00,93892.5,0,0,93892.5,Ready
3,ACI001,"AC, INC.",NaN,NaN,NaN,NaN,NaN,NaN,93892.5,0,0,93892.5,Ready
4,ALP001,ALPHA CHEMICAL SERVICES INC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ready
5,NaN,90122,O,2023-06-15 00:00:00,2023-07-15 00:00:00,2023-06-15 00:00:00,2023-06-15 00:00:00,2023-06-15 00:00:00,1206.31,0,0,1206.31,Ready
6,ALP001,ALPHA CHEMICAL SERVICES INC,NaN,NaN,NaN,NaN,NaN,NaN,1206.31,0,0,1206.31,Ready
7,AME007,AMERICAN LOBSTER PRODUCTS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ready
8,NaN,6997,O,2023-07-09 00:00:00,2023-07-10 00:00:00,2023-07-09 00:00:00,2023-07-09 00:00:00,2023-07-09 00:00:00,121475,0,0,121475,Ready
9,AME007,AMERICAN LOBSTER PRODUCTS,NaN,NaN,NaN,NaN,NaN,NaN,121475,0,0,121475,Ready
10,ANT004,ANTHEM BC & BS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ready
11,NaN,2023-08-01 00:00:00,O,2023-07-07 00:00:00,2023-07-08 00:00:00,2023-07-07 00:00:00,2023-07-07 00:00:00,2023-07-10 00:00:00,1177.24,0,0,1177.24,Ready
12,ANT004,ANTHEM BC & BS,NaN,NaN,NaN,NaN,NaN,NaN,1177.24,0,0,1177.24,Ready
13,ARA001,ARAHO TRANSFER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ready
14,NaN,6628061623,O,2023-06-16 00:00:00,2023-07-16 00:00:00,2023-06-16 00:00:00,2023-07-11 00:00:00,2023-07-11 00:00:00,225.62,0,0,225.62,Ready
15,ARA001,ARAHO TRANSFER,NaN,NaN,NaN,NaN,NaN,NaN,225.62,0,0,225.62,Ready
16,BAY003,"BAY HAVEN LOBSTER, INC.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ready
17,NaN,46706,O,2023-07-11 00:00:00,2023-07-18 00:00:00,2023-07-11 00:00:00,2023-07-11 00:00:00,2023-07-11 00:00:00,2409.25,0,0,2409.25,Ready
18,BAY003,"BAY HAVEN LOBSTER, INC.",NaN,NaN,NaN,NaN,NaN,NaN,2409.25,0,0,2409.25,Ready
19,BBX001,"BBX, INC",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ready
20,NaN,BX01080429,O,2023-07-03 00:00:00,2023-07-10 00:00:00,2023-07-03 00:00:00,2023-07-03 00:00:00,2023-07-07 00:00:00,172.79,0,0,172.79,Ready
21,NaN,BX01080781,O,2023-07-06 00:00:00,2023-07-13 00:00:00,2023-07-06 00:00:00,2023-07-06 00:00:00,2023-07-07 00:00:00,212.13,0,0,212.13,Ready
22,NaN,BX01080951,O,2023-07-07 00:00:00,2023-07-14 00:00:00,2023-07-07 00:00:00,2023-07-07 00:00:00,2023-07-11 00:00:00,145.77,0,0,145.77,Ready
23,BBX001,"BBX, INC",NaN,NaN,NaN,NaN,NaN,NaN,530.69,0,0,530.69,Ready
24,BLO002,BLOIS AUTOMATION,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ready
25,NaN,3731,O,2023-06-14 00:00:00,2023-07-14 00:00:00,2023-06-14 00:00:00,2023-06-14 00:00:00,2023-06-14 00:00:00,144.72,0,0,144.72,Ready
26,BLO002,BLOIS AUTOMATION,NaN,NaN,NaN,NaN,NaN,NaN,144.72,0,0,144.72,Ready
27,BOS001,BOSTON FLORIDA TRANSPORT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ready
28,NaN,6628061623,O,2023-06-16 00:00:00,2023-07-16 00:00:00,2023-06-16 00:00:00,2023-06-16 00:00:00,2023-06-26 00:00:00,217.5,0,0,217.5,Ready
29,NaN,6628061923,O,2023-06-19 00:00:00,2023-07-19 00:00:00,2023-06-19 00:00:00,2023-06-19 00:00:00,2023-07-03 00:00:00,97.5,0,0,97.5,Ready
30,NaN,6628062123,O,2023-06-21 00:00:00,2023-07-21 00:00:00,2023-06-21 00:00:00,2023-06-21 00:00:00,2023-07-03 00:00:00,112.5,0,0,112.5,Ready
31,BOS001,BOSTON FLORIDA TRANSPORT,NaN,NaN,NaN,NaN,NaN,NaN,427.5,0,0,427.5,Ready
32,BOS003,BOSTON SEAFOOD EXPRESS INC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ready
33,NaN,275491,O,2023-06-15 00:00:00,2023-07-15 00:00:00,2023-06-15 00:00:00,2023-06-15 00:00:00,2023-06-15 00:00:00,282.36,0,0,282.36,Ready
36,BOS003,BOSTON SEAFOOD EXPRESS INC,NaN,NaN,NaN,NaN,NaN,NaN,282.36,0,0,282.36,Ready
37,BRE002,BRENDAN READY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ready
38,NaN,110504,O,2023-07-10 00:00:00,2023-07-11 00:00:00,2023-07-10 00:00:00,2023-07-10 00:00:00,2023-07-10 00:00:00,720.25,0,0,720.25,Ready
39,BRE002,BRENDAN READY,NaN,NaN,NaN,NaN,NaN,NaN,720.25,0,0,720.25,Ready
40,BRI001,BRISTOL LOBSTER SALES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ready
41,NaN,126495,O,2023-07-06 00:00:00,2023-07-07 00:00:00,2023-07-06 00:00:00,2023-07-06 00:00:00,2023-07-06 00:00:00,10791,0,0,10791,Ready
42,NaN,126496,O,2023-07-09 00:00:00,2023-07-10 00:00:00,2023-07-09 00:00:00,2023-07-09 00:00:00,2023-07-09 00:00:00,21948,0,0,21948,Ready
43,NaN,126497,O,2023-07-11 00:00:00,2023-07-12 00:00:00,2023-07-11 00:00:00,2023-07-11 00:00:00,2023-07-12 00:00:00,11340,0,0,11340,Ready
44,BRI001,BRISTOL LOBSTER SALES,NaN,NaN,NaN,NaN,NaN,NaN,44079,0,0,44079,Ready
45,BTP001,"B&T PALLET RECYCLING, INC.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ready
46,NaN,11219,O,2023-07-02 00:00:00,2023-07-12 00:00:00,2023-07-02 00:00:00,2023-07-02 00:00:00,2023-06-30 00:00:00,1435,0,0,1435,Ready
47,BTP001,"B&T PALLET RECYCLING, INC.",NaN,NaN,NaN,NaN,NaN,NaN,1435,0,0,1435,Ready
48,BUT001,BUTLER BROS SUPPLY DIVISION,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ready
49,NaN,6408576,O,2023-06-20 00:00:00,2023-07-20 00:00:00,2023-06-20 00:00:00,2023-06-20 00:00:00,2023-06-20 00:00:00,3204,0,0,3204,Ready
50,BUT001,BUTLER BROS SUPPLY DIVISION,NaN,NaN,NaN,NaN,NaN,NaN,3204,0,0,3204,Ready
51,CAR001,"CARGO SERVICE CENTER, INC",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ready
52,NaN,AR150538,O,2023-06-22 00:00:00,2023-07-02 00:00:00,2023-06-22 00:00:00,2023-06-22 00:00:00,2023-06-26 00:00:00,3525,0,0,3525,Ready

In [28]:
#copy the vendor code to each empty cell in row 'Vendor' if it is empty 
#with the cell above
for i in range(2, len(e1)):
    if pd.isnull(e1.at[i, 'Vendor']):
        e1.at[i, 'Vendor'] = e1.at[i-1, 'Vendor'].astype(str)

KeyError: 34

In [29]:
e1.head(50)

,Vendor,Invoice,S,*================,Unnamed: 4,Dates ===================*,Unnamed: 6,Unnamed: 7,Invoice.1,Discount,Payments,Balance,Company
1,ACI001,"AC, INC.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ready
2,ACI001,121093,O,2023-07-09 00:00:00,2023-07-16 00:00:00,2023-07-09 00:00:00,2023-07-09 00:00:00,2023-07-09 00:00:00,93892.5,0,0,93892.5,Ready
3,ACI001,"AC, INC.",NaN,NaN,NaN,NaN,NaN,NaN,93892.5,0,0,93892.5,Ready
4,ALP001,ALPHA CHEMICAL SERVICES INC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ready
5,ALP001,90122,O,2023-06-15 00:00:00,2023-07-15 00:00:00,2023-06-15 00:00:00,2023-06-15 00:00:00,2023-06-15 00:00:00,1206.31,0,0,1206.31,Ready
6,ALP001,ALPHA CHEMICAL SERVICES INC,NaN,NaN,NaN,NaN,NaN,NaN,1206.31,0,0,1206.31,Ready
7,AME007,AMERICAN LOBSTER PRODUCTS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ready
8,AME007,6997,O,2023-07-09 00:00:00,2023-07-10 00:00:00,2023-07-09 00:00:00,2023-07-09 00:00:00,2023-07-09 00:00:00,121475,0,0,121475,Ready
9,AME007,AMERICAN LOBSTER PRODUCTS,NaN,NaN,NaN,NaN,NaN,NaN,121475,0,0,121475,Ready
10,ANT004,ANTHEM BC & BS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ready
11,ANT004,2023-08-01 00:00:00,O,2023-07-07 00:00:00,2023-07-08 00:00:00,2023-07-07 00:00:00,2023-07-07 00:00:00,2023-07-10 00:00:00,1177.24,0,0,1177.24,Ready
12,ANT004,ANTHEM BC & BS,NaN,NaN,NaN,NaN,NaN,NaN,1177.24,0,0,1177.24,Ready
13,ARA001,ARAHO TRANSFER,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ready
14,ARA001,6628061623,O,2023-06-16 00:00:00,2023-07-16 00:00:00,2023-06-16 00:00:00,2023-07-11 00:00:00,2023-07-11 00:00:00,225.62,0,0,225.62,Ready
15,ARA001,ARAHO TRANSFER,NaN,NaN,NaN,NaN,NaN,NaN,225.62,0,0,225.62,Ready
16,BAY003,"BAY HAVEN LOBSTER, INC.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ready
17,BAY003,46706,O,2023-07-11 00:00:00,2023-07-18 00:00:00,2023-07-11 00:00:00,2023-07-11 00:00:00,2023-07-11 00:00:00,2409.25,0,0,2409.25,Ready
18,BAY003,"BAY HAVEN LOBSTER, INC.",NaN,NaN,NaN,NaN,NaN,NaN,2409.25,0,0,2409.25,Ready
19,BBX001,"BBX, INC",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ready
20,BBX001,BX01080429,O,2023-07-03 00:00:00,2023-07-10 00:00:00,2023-07-03 00:00:00,2023-07-03 00:00:00,2023-07-07 00:00:00,172.79,0,0,172.79,Ready
21,BBX001,BX01080781,O,2023-07-06 00:00:00,2023-07-13 00:00:00,2023-07-06 00:00:00,2023-07-06 00:00:00,2023-07-07 00:00:00,212.13,0,0,212.13,Ready
22,BBX001,BX01080951,O,2023-07-07 00:00:00,2023-07-14 00:00:00,2023-07-07 00:00:00,2023-07-07 00:00:00,2023-07-11 00:00:00,145.77,0,0,145.77,Ready
23,BBX001,"BBX, INC",NaN,NaN,NaN,NaN,NaN,NaN,530.69,0,0,530.69,Ready
24,BLO002,BLOIS AUTOMATION,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ready
25,BLO002,3731,O,2023-06-14 00:00:00,2023-07-14 00:00:00,2023-06-14 00:00:00,2023-06-14 00:00:00,2023-06-14 00:00:00,144.72,0,0,144.72,Ready
26,BLO002,BLOIS AUTOMATION,NaN,NaN,NaN,NaN,NaN,NaN,144.72,0,0,144.72,Ready
27,BOS001,BOSTON FLORIDA TRANSPORT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ready
28,BOS001,6628061623,O,2023-06-16 00:00:00,2023-07-16 00:00:00,2023-06-16 00:00:00,2023-06-16 00:00:00,2023-06-26 00:00:00,217.5,0,0,217.5,Ready
29,BOS001,6628061923,O,2023-06-19 00:00:00,2023-07-19 00:00:00,2023-06-19 00:00:00,2023-06-19 00:00:00,2023-07-03 00:00:00,97.5,0,0,97.5,Ready
30,BOS001,6628062123,O,2023-06-21 00:00:00,2023-07-21 00:00:00,2023-06-21 00:00:00,2023-06-21 00:00:00,2023-07-03 00:00:00,112.5,0,0,112.5,Ready
31,BOS001,BOSTON FLORIDA TRANSPORT,NaN,NaN,NaN,NaN,NaN,NaN,427.5,0,0,427.5,Ready
32,BOS003,BOSTON SEAFOOD EXPRESS INC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ready
33,BOS003,275491,O,2023-06-15 00:00:00,2023-07-15 00:00:00,2023-06-15 00:00:00,2023-06-15 00:00:00,2023-06-15 00:00:00,282.36,0,0,282.36,Ready
36,BOS003,BOSTON SEAFOOD EXPRESS INC,NaN,NaN,NaN,NaN,NaN,NaN,282.36,0,0,282.36,Ready
37,BRE002,BRENDAN READY,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ready
38,NaN,110504,O,2023-07-10 00:00:00,2023-07-11 00:00:00,2023-07-10 00:00:00,2023-07-10 00:00:00,2023-07-10 00:00:00,720.25,0,0,720.25,Ready
39,BRE002,BRENDAN READY,NaN,NaN,NaN,NaN,NaN,NaN,720.25,0,0,720.25,Ready
40,BRI001,BRISTOL LOBSTER SALES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ready
41,NaN,126495,O,2023-07-06 00:00:00,2023-07-07 00:00:00,2023-07-06 00:00:00,2023-07-06 00:00:00,2023-07-06 00:00:00,10791,0,0,10791,Ready
42,NaN,126496,O,2023-07-09 00:00:00,2023-07-10 00:00:00,2023-07-09 00:00:00,2023-07-09 00:00:00,2023-07-09 00:00:00,21948,0,0,21948,Ready
43,NaN,126497,O,2023-07-11 00:00:00,2023-07-12 00:00:00,2023-07-11 00:00:00,2023-07-11 00:00:00,2023-07-12 00:00:00,11340,0,0,11340,Ready
44,BRI001,BRISTOL LOBSTER SALES,NaN,NaN,NaN,NaN,NaN,NaN,44079,0,0,44079,Ready
45,BTP001,"B&T PALLET RECYCLING, INC.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ready
46,NaN,11219,O,2023-07-02 00:00:00,2023-07-12 00:00:00,2023-07-02 00:00:00,2023-07-02 00:00:00,2023-06-30 00:00:00,1435,0,0,1435,Ready
47,BTP001,"B&T PALLET RECYCLING, INC.",NaN,NaN,NaN,NaN,NaN,NaN,1435,0,0,1435,Ready
48,BUT001,BUTLER BROS SUPPLY DIVISION,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ready
49,NaN,6408576,O,2023-06-20 00:00:00,2023-07-20 00:00:00,2023-06-20 00:00:00,2023-06-20 00:00:00,2023-06-20 00:00:00,3204,0,0,3204,Ready
50,BUT001,BUTLER BROS SUPPLY DIVISION,NaN,NaN,NaN,NaN,NaN,NaN,3204,0,0,3204,Ready
51,CAR001,"CARGO SERVICE CENTER, INC",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ready
52,NaN,AR150538,O,2023-06-22 00:00:00,2023-07-02 00:00:00,2023-06-22 00:00:00,2023-06-22 00:00:00,2023-06-26 00:00:00,3525,0,0,3525,Ready

In [7]:
# Drop rows based on missing the 'O' value. Invoices only show in 'O' rows
e1 = e1[e1['S'] == 'O']

In [8]:
# rename e2 title column and drop first 15 characters
e2 = e2.rename(columns={'Title': 'invoiceid'})
e2['invoiceid'] = e2['invoiceid'].str[15:]

In [9]:
# for e1 merge vendor and invoice to invoiceid
e1["invoiceid"] = e1['Vendor'].astype(str) +" "+ e1['Invoice'].astype(str)

/tmp/ipykernel_5947/2817250679.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e1["invoiceid"] = e1['Vendor'].astype(str) +" "+ e1['Invoice'].astype(str)

In [10]:
# Should prep the spreadsheet to avoid this issue. Will comment out later.
e1 = e1.rename(columns={'Unnamed: 7': 'Due Date'})
e1.head()

,Vendor,Invoice,S,*================,Unnamed: 4,Dates ===================*,Unnamed: 6,Due Date,Invoice.1,Discount,Payments,Balance,Company,invoiceid
2,ACI001,121093,O,2023-07-09 00:00:00,2023-07-16 00:00:00,2023-07-09 00:00:00,2023-07-09 00:00:00,2023-07-09 00:00:00,93892.5,0,0,93892.5,Ready,ACI001 121093
5,ALP001,90122,O,2023-06-15 00:00:00,2023-07-15 00:00:00,2023-06-15 00:00:00,2023-06-15 00:00:00,2023-06-15 00:00:00,1206.31,0,0,1206.31,Ready,ALP001 90122
8,AME007,6997,O,2023-07-09 00:00:00,2023-07-10 00:00:00,2023-07-09 00:00:00,2023-07-09 00:00:00,2023-07-09 00:00:00,121475,0,0,121475,Ready,AME007 6997
11,ANT004,2023-08-01 00:00:00,O,2023-07-07 00:00:00,2023-07-08 00:00:00,2023-07-07 00:00:00,2023-07-07 00:00:00,2023-07-10 00:00:00,1177.24,0,0,1177.24,Ready,ANT004 2023-08-01 00:00:00
14,ARA001,6628061623,O,2023-06-16 00:00:00,2023-07-16 00:00:00,2023-06-16 00:00:00,2023-07-11 00:00:00,2023-07-11 00:00:00,225.62,0,0,225.62,Ready,ARA001 6628061623

In [11]:
# merging dataframes
e3 = e1[["invoiceid","Due Date","Company"]].merge(e2[["invoiceid","Status","Sent to"]],on="invoiceid",how="left")

In [13]:
e3.head(60)

,invoiceid,Due Date,Company,Status,Sent to
0,ACI001 121093,2023-07-09 00:00:00,Ready,NaN,NaN
1,ALP001 90122,2023-06-15 00:00:00,Ready,NaN,NaN
2,AME007 6997,2023-07-09 00:00:00,Ready,NaN,NaN
3,ANT004 2023-08-01 00:00:00,2023-07-10 00:00:00,Ready,NaN,NaN
4,ARA001 6628061623,2023-07-11 00:00:00,Ready,Requested,"Evan Humphrey,Lyle Brown"
5,BAY003 46706,2023-07-11 00:00:00,Ready,NaN,NaN
6,BBX001 BX01080429,2023-07-07 00:00:00,Ready,Requested,"Evan Humphrey,Lyle Brown"
7,BBX001 BX01080781,2023-07-07 00:00:00,Ready,Requested,"Lyle Brown,Evan Humphrey"
8,BBX001 BX01080951,2023-07-11 00:00:00,Ready,NaN,NaN
9,BLO002 3731,2023-06-14 00:00:00,Ready,NaN,NaN
10,BOS001 6628061623,2023-06-26 00:00:00,Ready,NaN,NaN
11,BOS001 6628061923,2023-07-03 00:00:00,Ready,NaN,NaN
12,BOS001 6628062123,2023-07-03 00:00:00,Ready,NaN,NaN
13,BOS003 275491,2023-06-15 00:00:00,Ready,Requested,"Evan Humphrey,Lyle Brown"
14,nan 110504,2023-07-10 00:00:00,Ready,NaN,NaN
15,nan 126495,2023-07-06 00:00:00,Ready,NaN,NaN
16,nan 126496,2023-07-09 00:00:00,Ready,NaN,NaN
17,nan 126497,2023-07-12 00:00:00,Ready,NaN,NaN
18,nan 11219,2023-06-30 00:00:00,Ready,NaN,NaN
19,nan 6408576,2023-06-20 00:00:00,Ready,NaN,NaN
20,nan AR150538,2023-06-26 00:00:00,Ready,NaN,NaN
21,nan AR150546,2023-06-26 00:00:00,Ready,NaN,NaN
22,nan AR150547,2023-06-26 00:00:00,Ready,NaN,NaN
23,nan AR150548,2023-06-26 00:00:00,Ready,NaN,NaN
24,nan AR150549,2023-06-26 00:00:00,Ready,NaN,NaN
25,nan AR150552,2023-06-26 00:00:00,Ready,NaN,NaN
26,nan AR150553,2023-06-26 00:00:00,Ready,NaN,NaN
27,nan AR150558,2023-06-27 00:00:00,Ready,NaN,NaN
28,nan AR150559,2023-06-27 00:00:00,Ready,NaN,NaN
29,nan AR150574,2023-06-30 00:00:00,Ready,NaN,NaN
30,nan AR150576,2023-06-30 00:00:00,Ready,NaN,NaN
31,nan AR150577,2023-06-30 00:00:00,Ready,NaN,NaN
32,nan AR150590,2023-07-03 00:00:00,Ready,NaN,NaN
33,nan AR150591,2023-07-03 00:00:00,Ready,NaN,NaN
34,nan AR150592,2023-07-03 00:00:00,Ready,NaN,NaN
35,nan AR150593,2023-07-03 00:00:00,Ready,NaN,NaN
36,nan AR150597,2023-07-07 00:00:00,Ready,NaN,NaN
37,nan AR150598,2023-07-07 00:00:00,Ready,NaN,NaN
38,nan AR150604,2023-07-07 00:00:00,Ready,NaN,NaN
39,nan AR150605,2023-07-07 00:00:00,Ready,NaN,NaN
40,nan AR150606,2023-07-07 00:00:00,Ready,NaN,NaN
41,nan 2023-24263,2023-06-12 00:00:00,Ready,NaN,NaN
42,nan 2023-24343,2023-06-15 00:00:00,Ready,NaN,NaN
43,nan 25402,2023-07-07 00:00:00,Ready,NaN,NaN
44,nan 25404,2023-07-09 00:00:00,Ready,NaN,NaN
45,nan 25405,2023-07-10 00:00:00,Ready,NaN,NaN
46,nan 25406,2023-07-12 00:00:00,Ready,NaN,NaN
47,nan 25407,2023-07-11 00:00:00,Ready,NaN,NaN
48,nan 25409,2023-07-11 00:00:00,Ready,NaN,NaN
49,nan 55239,2023-06-08 00:00:00,Ready,NaN,NaN
50,nan 55242,2023-06-09 00:00:00,Ready,NaN,NaN
51,nan 010723JC,2023-07-05 00:00:00,Ready,NaN,NaN
52,nan 405531,2023-06-07 00:00:00,Ready,NaN,NaN
53,nan 405612,2023-06-19 00:00:00,Ready,NaN,NaN
54,nan 405636,2023-06-22 00:00:00,Ready,NaN,NaN
55,nan BO-180968,2023-06-15 00:00:00,Ready,NaN,NaN
56,nan BO-180996,2023-06-16 00:00:00,Ready,NaN,NaN
57,nan BO-181089,2023-06-19 00:00:00,Ready,NaN,NaN
58,nan 1207668565,2023-07-10 00:00:00,Ready,NaN,NaN
59,nan V6-89735,2023-06-26 00:00:00,Ready,NaN,NaN